MelodyHub/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home_new, name='home_new'),
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls')),
    path('music_album/', include('music_album.urls')),
    path('learn_forms/', include('learn_forms.urls')),
]

learn_forms/urls.py
from django.urls import path
from learn_forms import views

app_name = "learn_forms"

urlpatterns = [

    path('form_one/', views.form_one, name = 'form_one'),
    path('form_two/', views.form_two, name = 'form_two'),
    path('form_three/', views.form_three, name = 'form_three'),
    path('form_four/', views.form_four, name = 'form_four'),
    path('musician_form/', views.musician_form, name = 'musician_form'),


]

music_album/urls.py
from django.urls import path
from music_album import views

app_name = "music_album"

urlpatterns = [

    path('list_musician/', views.list_musician, name='list_musician'),
    path('test_one/', views.test_one, name='test_one'),

    # CRUD Operation
    path('home_page/', views.home_page, name='home_page'),
    path('album_list/', views.album_list, name='album_list'),
    path('album_form/', views.album_form, name='album_form'),
    path('musician_list/', views.musician_list, name='musician_list'),
    path('musician_form/', views.musician_form, name='musician_form'),

    path('individual_album_list/<int:artist_id>/',
         views.individual_album_list, name='individual_album_list'),
    path('edit_artist/<int:artist_id>/', views.edit_artist, name='edit_artist'),
    path('edit_album/<int:album_id>/', views.edit_album, name='edit_album'),
    path('delete_album/<int:album_id>/',
         views.delete_album, name='delete_album'),
    path('delete_musician/<int:artist_id>/',
         views.delete_musician, name='delete_musician'),

    path('sample_file_details/', views.sample_file_details,
         name='disp_sample_file_details'),

]

music_album/models.py
from django.db import models

# Create your models here.


class Musician(models.Model):
    # id = models.AutoField(primary_key=True)
    # The above line is auto generated by django when we migrate
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Album(models.Model):
    # id = models.AutoField(primary_key=True)
    # The above line is auto generated by django when we migrate
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()
    rating = (

        (1, "Worst"),
        (2, "Bad"),
        (3, "Not Bad"),
        (4, "Good"),
        (5, "Excellent"),

    )
    num_stars = models.IntegerField(choices=rating)

    # When we use one class inside the another class we use Meta Keyword

    def __str__(self):
        return self.name + ", Rating - " + str(self.num_stars)


class UploadSamplFile(models.Model):
    file_name = models.CharField(max_length=1000)
    sample_file = models.FileField(
        upload_to='sample_files/')

    def __str__(self):
        file_name = self.sample_file.name.split("/")[-1]
        return file_name

music_album/forms.py
from django import forms
from music_album.models import Album, Musician, UploadSamplFile
from django.forms.widgets import ClearableFileInput


class MusicianForm(forms.ModelForm):
    class Meta:
        model = Musician
        fields = "__all__"


class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(
        widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Album
        fields = "__all__"


class UploadSamplFileForm(forms.ModelForm):
    file_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'file_name', 'style': 'width: 300px;', 'class': 'form-control'}))
    sample_file = forms.FileField(widget=ClearableFileInput(
        attrs={'class': 'form-control', 'style': 'width: 1000px;', 'accept': '.pdf'}), max_length=600)

    class Meta:
        model = UploadSamplFile
        fields = '__all__'

music_album/views.py
from .forms import UploadSamplFileForm
from django.shortcuts import render, redirect
from music_album.models import Musician, Album
from music_album import forms
from django.db.models import Avg

# Create your views here.


def list_musician(request):
    musician_list = Musician.objects.order_by('first_name')
    dict_data = {'text': "This is the list of Musicians",
                 'musician': musician_list}
    return render(request, 'music_album/musician.html', context=dict_data)


def test_one(request):
    data_passing = {'sample_text': 'Learning Template Inheritence',
                    'sample_data': 'Nav bar is from layout/base.html and Inherited in this page using template Inheritence',
                    'text_one': 'our perseption is our reality',
                    'text_two': 'WHAT YOU THINK YOU BECOME',
                    'text_three': '10',
                    'text_four': 'believe in yourself',
                    'text_five': 'django uses ORM',
                    'text_six': 'Get the Album data from admin',
                    'get_album': Album.objects.get(pk=1),
                    'text_seven': 'To check filters working - ',
                    }
    return render(request, 'music_album/test_one.html', context=data_passing)

# =============================================================================================================================
# CRUD Operation indjango


def home_page(request):
    album_data = {
        'title': 'Home Page',
    }
    return render(request, 'music_album/home.html', context=album_data)


def album_list(request):
    get_albums = Album.objects.order_by('artist')
    album_data = {
        'title': 'List of Albums',
        'album_list': get_albums,
    }
    return render(request, 'music_album/album_list.html', context=album_data)


def album_form(request):
    load_album_form = forms.AlbumForm()

    if request.method == 'POST':
        load_album_form = forms.AlbumForm(request.POST)

        if load_album_form.is_valid():
            load_album_form.save(commit=True)
            return album_list(request)

    album_data = {
        'title': 'Add Album',
        'album_form': load_album_form
    }
    return render(request, 'music_album/album_form.html', context=album_data)


def musician_list(request):
    get_musicians = Musician.objects.order_by('first_name')
    musician_data = {
        'title': 'List of Musicians',
        'musician_list': get_musicians,
    }
    return render(request, 'music_album/musician_list.html', context=musician_data)


def musician_form(request):
    load_musician_form = forms.MusicianForm()

    if request.method == 'POST':
        load_musician_form = forms.MusicianForm(request.POST)

        if load_musician_form.is_valid():
            load_musician_form.save(commit=True)
            return musician_list(request)

    album_data = {
        'title': 'Add Musician',
        'musician_form': load_musician_form,

    }
    return render(request, 'music_album/musician_form.html', context=album_data)


def individual_album_list(request, artist_id):
    get_artist_info = Musician.objects.get(pk=artist_id)
    get_album_list = Album.objects.filter(artist=artist_id).order_by('name')
    get_artist_rating = Album.objects.filter(
        artist=artist_id).aggregate(Avg('num_stars'))
    album_data = {
        'title': 'Individual Album List',
        'artist_info': get_artist_info,
        'ind_album_list': get_album_list,
        'artist_rating': get_artist_rating,
    }
    return render(request, 'music_album/individual_album_list.html', context=album_data)


def edit_artist(request, artist_id):
    get_artist_info = Musician.objects.get(pk=artist_id)
    get_artist_form = forms.MusicianForm(instance=get_artist_info)
    artist_data = {'title': 'Edit Artist', }

    if request.method == 'POST':
        get_artist_form = forms.MusicianForm(
            request.POST, instance=get_artist_info)

        if get_artist_form.is_valid():
            get_artist_form.save(commit=True)
            artist_data.update(
                {'success_text': 'Artist Data Successfully Updated !'})
            return individual_album_list(request, artist_id)

    artist_data.update({'edit_from': get_artist_form, })
    return render(request, 'music_album/edit_artist.html', context=artist_data)


def edit_album(request, album_id):
    get_album_info = Album.objects.get(pk=album_id)
    get_album_form = forms.AlbumForm(instance=get_album_info)
    album_data = {'title': 'Edit Album', }

    if request.method == 'POST':
        get_album_form = forms.AlbumForm(request.POST, instance=get_album_info)

        if get_album_form.is_valid():
            get_album_form.save(commit=True)
            album_data.update({'success_text': 'Album Successfully Updated !'})

    album_data.update({'edit_from': get_album_form, })
    album_data.update({'album_id': album_id, })
    return render(request, 'music_album/edit_album.html', context=album_data)


def delete_album(request, album_id):
    get_album_to_delete = Album.objects.get(pk=album_id).delete()
    delete_album_data = {'delete_success': 'Album Deleted Successfully !'}
    return render(request, 'music_album/delete_page.html', context=delete_album_data)


def delete_musician(request, artist_id):
    get_musician_to_delete = Musician.objects.get(pk=artist_id).delete()
    delete_musician_data = {
        'delete_success': 'Musician Deleted Successfully !'}
    return render(request, 'music_album/delete_page.html', context=delete_musician_data)


def sample_file_details(request):
    if request.method == 'POST':
        form = UploadSamplFileForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            form.save()
            return redirect('home_page')

    form = UploadSamplFileForm()
    return render(request, 'music_album/select_headers.html', {'form': form})


# def dexma_app_cred_home(request):
#     if request.method == "POST":,
#         app_id = request.POST.get("dexma_app_id", ' ').strip()
#         app_secret_id = request.POST.get("dexma_app_secret_id", ' ').strip()
#         app_cred = DexmaAppCredentials.objects.first()
#         if app_cred:
#             app_cred.dexma_app_id = app_id
#             app_cred.dexma_app_secret_id = app_secret_id
#             app_cred.save()
#         else:
#             app_cred = DexmaAppCredentials(
#                 dexma_app_id=app_id, dexma_app_secret_id=app_secret_id)
#             app_cred.save()
#         return redirect('display_dexama_app_cred')
#     return render(request, "test_app/dexma_app_cred_submit.html")

templates/music_album/album_form.html
{% extends "layout/base_ma.html" %}

{% load my_filters %}

{% block body_block %}

<h1>Album Form</h1>

<form method="POST">

    {{ album_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add Album" class="btn btn-primary btn-sm">

</form>


{% endblock %}

templates/music_album/album_list.html
{% extends "layout/base_ma.html" %}

{% load my_filters %}

{% block body_block %}

<h1>Album List</h1>

<ul>

    {% if album_list %}

    {% for album in album_list %}
    <li>

        {{ album.artist }} : {{ album.name }}

    </li>
    {% endfor %}

    {% else %}

    <h3>No Album found  in the Database</h3>

    {% endif %}

</ul>

{% endblock %}

templates/music_album/delete_page.html
{% extends "layout/base_ma.html" %}

{% block body_block %}

<h3>Delete Message Page</h3>

<div class="alert alert-danger">
    {{ delete_success }}
</div>

{% endblock %}

templates/music_album/edit_album.html
{% extends "layout/base_ma.html" %}

{% block body_block %}

<h3>Edit Artist</h3>

{% if success_text %}

<div class="alert alert-success">
    {{ success_text }}
</div>

{% endif %}

<form method="POST">
    {{ edit_from.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm">
</form>

<br>

<a href="{% url 'music_album:delete_album' album_id=album_id %}" class="btn btn-danger btn-sm" onclick="return confirm('Delete This Album?')">Delete</a>

{% endblock %}

templates/music_album/edit_artist.html
{% extends "layout/base_ma.html" %}

{% block body_block %}

<h3>Edit Artist</h3>

{% if success_text %}

<div class="alert alert-success">

    {{ success_text }}

</div>

{% endif %}

<form method="POST">
    {{ edit_from.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm">
</form>

{% endblock %}

templates/music_album/home.html
{% extends "layout/base_ma.html" %}

{% load my_filters %}

{% block body_block %}

<h1>Home Page</h1>

{% endblock %}

templates/music_album/individual_album_list.html
{% extends "layout/base_ma.html" %}

{% load my_filters %}

{% block body_block %}

<h1>Individual Album List</h1>

<h4> Artist Info : {{ artist_info.first_name }} {{ artist_info.last_name }}</h4>
<h4> Instrument Name : {{ artist_info.instrument }}</h4>
<h4> Artist Rating : {{ artist_rating.num_stars__avg }}</h4>

<hr>

<a href="{% url 'music_album:edit_artist' artist_id=artist_info.id %}" class="btn btn-primary btn-md">Edit</a>

<br>
<br>

<table class="table table-bordered">
    <tr>
        <th>Album Name</th>
        <th>Release Date</th>
        <th>Rating</th>
    </tr>

    {% for album in ind_album_list %}

    <tr>

        <td><a href="{% url 'music_album:edit_album' album_id=album.id %}">{{album.name}}</a></td>
        <td>{{album.release_date}}</td>
        <td>{{album.num_stars}}</td>

    </tr>

    {% endfor %}
    
</table>

<hr>

<a href="{% url 'music_album:delete_musician' artist_id=artist_info.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Delete This Album?')">Delete</a>

{% endblock %}

templates/music_album/musician.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Musician List</title>
  </head>
  <body>

    <h1>Musicians include songwriters who write both music and lyrics for songs, conductors who direct a musical performance, or performers who perform for an audience.</h1>

    <h2>A music performer is generally either a singer who provides vocals or an instrumentalist who plays a musical instrument.</h2>

    <img src="{% static 'images/mus.jpeg'%}" alt="">

    <br>

    <a href="{% url 'learn_forms:musician_form' %}">Add New Musician</a>

    <br>
    
    <h2>{{text}}</h2>

    <table border="1">

      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Instrument</th>
      </tr>

      {% for row in musician %}

      <tr>
        <td>{{ row.first_name }}</td>
        <td>{{ row.last_name }}</td>
        <td>{{ row.instrument }}</td>
      </tr>

      {% endfor %}

    </table>


  </body>
</html>

templates/music_album/musician_form.html
{% extends "layout/base_ma.html" %}

{% load my_filters %}

{% block body_block %}

<h1>Musician Form</h1>

<form method="POST">

    {{ musician_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add Musician" class="btn btn-primary btn-sm">

</form>

{% endblock %}

templates/music_album/musician_list.html
{% extends "layout/base_ma.html" %}

{% load my_filters %}

{% block body_block %}

<h1>Musician List</h1>

<ul>

    {% if musician_list %}

    {% for musician in musician_list %}

    <li><a href="{% url 'music_album:individual_album_list' artist_id=musician.id %}">{{ musician.first_name }} {{ musician.last_name }}</a></li>

    {% endfor %}

    {% else %}

    <h3>No Musicians found in the Database</h3>

    {% endif %}

</ul>

{% endblock %}

templates/music_album/select_headers.html
{% extends "layout/base_ma.html" %}



{% block title %}
upload_sample
{% endblock %}



{% block body_block %}
  

<div class="container h-100 mt-4">
  <div class="row h-100 justify-content-center align-items-center">
      <div class="col-xl-12">
          <div class="text-center">
              <h1 class="text-black mb-4">Upload Sample</h1>
              <div class="card custom-card"  style=background-color:#dde2e9;>
                  <form method="POST" enctype="multipart/form-data" >
                      {% csrf_token %}
                      <div class="form-group"></div>
                      <div class="form-group row justify-content-center medium-form-width medium-date-time">
                        <label  class="col-md-12 text-center"><b>File Name</b></label>
                        {{ form.file_name }}
                      </div>
                      <div class="form-group row justify-content-center medium-form-width">
                        <label for="csv-data-dropdown" class="col-md-12 text-center"><b>Sample File</b></label>
                        
                          {{ form.sample_file }}
                    </div>
                      <div class="text-center mt-4">
                          <button type="submit" class="btn btn-primary">Submit</button>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>

      {% load static %} 

<link rel="stylesheet" type="text/css" href="{% static 'css/upload_sample.css' %}">

 {% endblock %}

templates/music_album/test_one.html
{% extends "layout/base.html" %}

{% load my_filters %}

{% block body_block %}

<h2>{{ sample_text }}</h2>

<h3>{{ sample_data }}</h3>
<br>
<h4>{{ text_one|upper }}</h4>
<h4>{{ text_two|lower }}</h4>
<h4>{{ text_three|add:8 }}</h4>
<h4>{{ text_four|capfirst }}</h4>
<h4>{{ text_five|cut:'d' }}</h4>
<br>
<h4>{{ text_six }}</h4>
<br>
<h4>Album Name: {{ get_album.artist }}</h4>
<h4>Artist Name: {{ get_album.name }}</h4>
<h4>Release Date: {{ get_album.release_date|date:"D, d M Y" }}</h4>
<h4>Number of Stars: {{ get_album.num_stars }}</h4>

<h4>{{ text_seven|custom_filter }}</h4>


{% endblock %}