MelodyHub/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home_new, name='home_new'),
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls')),
    path('music_album/', include('music_album.urls')),
    path('learn_forms/', include('learn_forms.urls')),
]

learn_forms/urls.py
from django.urls import path
from learn_forms import views

app_name = "learn_forms"

urlpatterns = [

    path('form_one/', views.form_one, name = 'form_one'),
    path('form_two/', views.form_two, name = 'form_two'),
    path('form_three/', views.form_three, name = 'form_three'),
    path('form_four/', views.form_four, name = 'form_four'),
    path('musician_form/', views.musician_form, name = 'musician_form'),


]

music_album/urls.py
from django.urls import path
from music_album import views

app_name = "music_album"

urlpatterns = [

    path('list_musician/', views.list_musician, name='list_musician'),
    path('test_one/', views.test_one, name='test_one'),

    # CRUD Operation
    path('home_page/', views.home_page, name='home_page'),
    path('album_list/', views.album_list, name='album_list'),
    path('album_form/', views.album_form, name='album_form'),
    path('musician_list/', views.musician_list, name='musician_list'),
    path('musician_form/', views.musician_form, name='musician_form'),

    path('individual_album_list/<int:artist_id>/',
         views.individual_album_list, name='individual_album_list'),
    path('edit_artist/<int:artist_id>/', views.edit_artist, name='edit_artist'),
    path('edit_album/<int:album_id>/', views.edit_album, name='edit_album'),
    path('delete_album/<int:album_id>/',
         views.delete_album, name='delete_album'),
    path('delete_musician/<int:artist_id>/',
         views.delete_musician, name='delete_musician'),

    path('sample_file_details/', views.sample_file_details,
         name='disp_sample_file_details'),

]

templates/layout/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django Project</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Bootstrap CSS End-->

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- Bootstrap JS End -->

  </head>
  <body>

    <!-- Bootstrap Nav Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">


        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'music_album:test_one' %}">Home</a>
            <a class="nav-item nav-link active" href="{% url 'music_album:list_musician' %}">List Musician</a>
            <a class="nav-item nav-link active" href="{% url 'learn_forms:musician_form' %}">Musician Form</a>
        </div>

    </nav>
    <!-- Bootstrap Nav Bar End-->

    <div class="container">

        {% block body_block %}

        {% endblock %}

    </div>



  </body>
</html>

templates/layout/base_ma.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Bootstrap CSS End-->

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- Bootstrap JS End -->

  </head>
  <body>

    <!-- Bootstrap Nav Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">


        <div class="navbar-nav">

          <a class="nav-item nav-link active" href="{% url 'music_album:home_page' %}">Home</a>
          <a class="nav-item nav-link active" href="{% url 'music_album:album_list' %}">List-Alb</a>
          <a class="nav-item nav-link active" href="{% url 'music_album:musician_list' %}">List-Mus</a>
          <a class="nav-item nav-link active" href="{% url 'music_album:musician_form' %}">Add-Mus</a>
          <a class="nav-item nav-link active" href="{% url 'music_album:album_form' %}">Add-Alb</a>
            
        </div>

    </nav>
    <!-- Bootstrap Nav Bar End-->

    <div class="container">

        {% block body_block %}

        {% endblock %}

    </div>



  </body>
</html>